image: node:lts

services:
  - name: postgres:16-alpine
    alias: postgres

variables:
  PIPELINE: true
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST_AUTH_METHOD: trust

  AUTH_SECRET: test-secret
  ADMIN_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/admin
  ITEMS_SERVICE_URL: http://localhost:4500/graphql
  NEXT_PUBLIC_GOOGLE_CLIENT_ID: test-client-id
  LOGIN_SERVICE_URL: http://localhost:4010/api/v0

stages:
  # - quality
  - build
  - test

before_script:
  - npm run cis

# quality:
#   stage: quality
#   script:
#     - npm run lint
#     - npm --prefix Service/ItemsService run lint
#     - npm --prefix Service/ItemsService run cpd
#     - npm --prefix App/shopper run cpd

build:
  stage: build
  script:
    - npm run build

test:
  stage: test
  script:
    - npm run test
    - npm --prefix Service/ItemsService test
