services:
  app:
    container_name: app
    env_file: .env
    image: pouriarez/marketplace:latest
    environment:
      - NODE_ENV=production
    build:
      context: .
      args:
        ADMIN_DATABASE_URL: ${ADMIN_DATABASE_URL}
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "3002:3002"
      - "3010:3010"
  postgres:
    container_name: database
    image: postgres:alpine
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./Service/Login/sql/databases.sql:/docker-entrypoint-initdb.d/01.databases.sql
      - ./Service/Login/sql/schema.sql:/docker-entrypoint-initdb.d/02.schema.sql
      - ./Service/ItemsService/src/sql/databases.sql:/docker-entrypoint-initdb.d/03.databases.sql
      - ./Service/ItemsService/src/sql/schema.sql:/docker-entrypoint-initdb.d/04.schema.sql
      - ./Service/ItemsService/src/sql/data.sql:/docker-entrypoint-initdb.d/05.data.sql
      - ./App/seller/server/sql/databases.sql:/docker-entrypoint-initdb.d/06.databases.sql
      - ./App/seller/server/sql/schema.sql:/docker-entrypoint-initdb.d/07.schema.sql
      - ./App/admin/db/databases.sql:/docker-entrypoint-initdb.d/08.databases.sql
      - ./App/admin/db/schema.sql:/docker-entrypoint-initdb.d/09.schema.sql
      - ./App/admin/db/data.sql:/docker-entrypoint-initdb.d/10.data.sql