services:
  postgres:
    container_name: shopper-db
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ../sql/databases.sql:/docker-entrypoint-initdb.d/1.databases.sql
      - ../sql/schema.sql:/docker-entrypoint-initdb.d/2.schema.sql
    networks:
      - shared-network

  shopper-service:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ITEMS_SERVICE_URL: http://items-service:4000/graphql
    networks:
      - shared-network

networks:
  shared-network:
    external: true